import type {Todo} from './types'

export const initialTodos: Todo[] = [
  {
    id: '1',
    title: 'Design system tokens',
    description: 'Finalize color palette and spacing scale for Harmonium v2',
    completed: true,
    priority: 'high',
    category: 'Design',
    createdAt: new Date('2026-02-20'),
  },
  {
    id: '2',
    title: 'Build Button component',
    description: 'Primary, secondary, outline, and ghost variants with all sizes',
    completed: true,
    priority: 'high',
    category: 'Development',
    createdAt: new Date('2026-02-21'),
  },
  {
    id: '3',
    title: 'Write component tests',
    description: 'Vitest + Testing Library for all interactive components',
    completed: false,
    priority: 'medium',
    category: 'Development',
    createdAt: new Date('2026-02-23'),
  },
  {
    id: '4',
    title: 'Storybook documentation',
    description: 'Add stories with usage examples for every component',
    completed: false,
    priority: 'medium',
    category: 'Documentation',
    createdAt: new Date('2026-02-24'),
  },
  {
    id: '5',
    title: 'Accessibility audit',
    description: 'Run axe-core and screen reader testing on all components',
    completed: false,
    priority: 'high',
    category: 'Quality',
    createdAt: new Date('2026-02-25'),
  },
  {
    id: '6',
    title: 'Publish alpha to npm',
    description: 'Publish 2.0.0-alpha.0 with --tag next',
    completed: false,
    priority: 'low',
    category: 'Release',
    createdAt: new Date('2026-02-26'),
  },
  {
    id: '7',
    title: 'Performance benchmarks',
    description: 'Measure bundle size and rendering performance',
    completed: false,
    priority: 'low',
    category: 'Quality',
    createdAt: new Date('2026-02-27'),
  },
]
