import StyleDictionary from 'style-dictionary'
import {fileURLToPath} from 'node:url'
import {dirname, resolve} from 'node:path'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)
const rootDir = resolve(__dirname, '../../../..')
const tokensDir = resolve(rootDir, 'design-tokens')
const outDir = resolve(__dirname)

function flattenTokens(
  obj: Record<string, unknown>,
  prefix = '',
  result: Record<string, string> = {},
): Record<string, string> {
  for (const [key, val] of Object.entries(obj)) {
    if (key.startsWith('$')) continue
    const name = prefix ? `${prefix}-${key}` : key
    if (
      val &&
      typeof val === 'object' &&
      !Array.isArray(val) &&
      '$value' in (val as Record<string, unknown>)
    ) {
      result[name] = String((val as Record<string, unknown>)['$value'])
    } else if (val && typeof val === 'object' && !Array.isArray(val)) {
      flattenTokens(val as Record<string, unknown>, name, result)
    }
  }
  return result
}

async function build() {
  const sd = new StyleDictionary({
    source: [`${tokensDir}/**/*.json`],
    platforms: {
      css: {
        transformGroup: 'css',
        prefix: 'harmonium',
        buildPath: `${outDir}/`,
        files: [
          {
            destination: 'tokens.css',
            format: 'css/variables',
            options: {
              outputReferences: true,
            },
          },
        ],
      },
    },
  })

  await sd.buildAllPlatforms()

  // Also generate a TypeScript constants file
  const {readdir, readFile, writeFile} = await import('node:fs/promises')
  const {join} = await import('node:path')

  async function readJsonFiles(dir: string): Promise<Record<string, unknown>> {
    const entries = await readdir(dir, {withFileTypes: true})
    let merged: Record<string, unknown> = {}
    for (const entry of entries) {
      const fullPath = join(dir, entry.name)
      if (entry.isDirectory()) {
        const sub = await readJsonFiles(fullPath)
        merged = deepMerge(merged, sub)
      } else if (entry.name.endsWith('.json')) {
        const content = JSON.parse(await readFile(fullPath, 'utf-8'))
        merged = deepMerge(merged, content)
      }
    }
    return merged
  }

  function deepMerge(
    target: Record<string, unknown>,
    source: Record<string, unknown>,
  ): Record<string, unknown> {
    const result = {...target}
    for (const [key, val] of Object.entries(source)) {
      if (
        val &&
        typeof val === 'object' &&
        !Array.isArray(val) &&
        result[key] &&
        typeof result[key] === 'object' &&
        !Array.isArray(result[key])
      ) {
        result[key] = deepMerge(
          result[key] as Record<string, unknown>,
          val as Record<string, unknown>,
        )
      } else {
        result[key] = val
      }
    }
    return result
  }

  const allTokens = await readJsonFiles(tokensDir)
  const flat = flattenTokens(allTokens)

  const tsLines = Object.entries(flat)
    .map(([key, value]) => {
      const constName = key
        .replace(/[.-]/g, '_')
        .replace(/([a-z])([A-Z])/g, '$1_$2')
        .toUpperCase()
      const cssVar = `--harmonium-${key}`
      return `export const ${constName} = 'var(${cssVar})' as const`
    })
    .join('\n')

  const tsContent = `// Auto-generated by design token build. Do not edit.\n\n${tsLines}\n`
  await writeFile(join(outDir, 'tokens.ts'), tsContent)

  console.log('Design tokens built successfully.')
  console.log(`  CSS: ${outDir}/tokens.css`)
  console.log(`  TS:  ${outDir}/tokens.ts`)
}

build().catch((err) => {
  console.error('Token build failed:', err)
  process.exit(1)
})
